baseurl = "https://example.com/"
copyright = "© 2014 Copyright Text"
languageCode = "en-us"
paginate = 3
paginatePath = "page"
theme = "hugo-material-blog"
title = "Material Blog"
[languages.en]
languageName = "English"
[[languages.en.menu.footer1]]
name = "Service 1"
url = "#"
weight = 1
[[languages.en.menu.footer1]]
name = "Service 2"
url = "#"
weight = 2
[[languages.en.menu.footer2]]
name = "Home"
url = "/"
weight = 1
[[languages.en.menu.footer2]]
name = "About"
url = "/about/"
weight = 2
[[languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1
[[languages.en.params.footer_menus]]
menu = "footer2"
name = "Services"
[[languages.en.params.footer_menus]]
menu = "footer1"
name = "Links"
[languages.fr]
languageName = "Français"
[[languages.fr.menu.footer1]]
name = "Service 1"
url = "#"
weight = 1
[[languages.fr.menu.footer1]]
name = "Service 2"
url = "#"
weight = 2
[[languages.fr.menu.footer2]]
name = "Accueil"
url = "/fr/"
weight = 1
[[languages.fr.menu.footer2]]
name = "Sur"
url = "/about/"
weight = 2
[[languages.fr.menu.main]]
name = "Accueil"
url = "/fr/"
weight = 1
[[languages.fr.params.footer_menus]]
menu = "footer2"
name = "Services"
[[languages.fr.params.footer_menus]]
menu = "footer1"
name = "Links"
[params]
[permalinks]
defaultContentLanguage = "en"
post = "/:year/:month/:title/"
